// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6RTGsFt5orN9kjnvM7Iptc1a_PRS6OuU',
    appId: '1:13420289918:web:57c6ce3e0168d87f539d2f',
    messagingSenderId: '13420289918',
    projectId: 'ard-bazar',
    authDomain: 'ard-bazar.firebaseapp.com',
    storageBucket: 'ard-bazar.firebasestorage.app',
    measurementId: 'G-7K05CC86TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCCswGusBTPo0JerTn-An6Ic00sjpRJE',
    appId: '1:13420289918:android:72692759ab111419539d2f',
    messagingSenderId: '13420289918',
    projectId: 'ard-bazar',
    storageBucket: 'ard-bazar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_1rd5sToWnLy7rF0Kpn8RGyz09SiRV1Y',
    appId: '1:13420289918:ios:c60e8aab8f52d5a4539d2f',
    messagingSenderId: '13420289918',
    projectId: 'ard-bazar',
    storageBucket: 'ard-bazar.firebasestorage.app',
    iosBundleId: 'com.ard.ardApp',
  );
}

